source 'https://rubygems.org'

gem 'pg'
gem 'pry'
#gem 'active_model_serializers'
gem "active_model_serializers", github: "rails-api/active_model_serializers"
gem 'active_record_migrations'
gem 'docker-api'
gem 'hutch'
