source 'https://rubygems.org'

gem 'rails', '4.2.4'

# Rails extensions
gem "active_model_serializers", github: "rails-api/active_model_serializers"
#gem 'actioncable', github: 'rails/actioncable'
gem 'sprockets'
gem 'therubyracer'
gem 'httparty'

# DB related
gem 'pg'

#Asset related
gem 'haml-rails'
gem 'sass-rails', '~> 5.0'
gem 'compass-rails', github: "Compass/compass-rails", branch: "master"
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

# Misc
gem 'aasm'

# Environment management related
gem 'net-ssh'
gem 'net-ping'
gem 'docker-api'

# Web related
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
#gem 'sdoc', '~> 0.4.0', group: :doc
gem 'angular_rails_csrf'

source 'https://rails-assets.org' do
  gem 'rails-assets-lodash'
  gem 'rails-assets-angular'
  gem 'rails-assets-ui-router'
  gem 'rails-assets-ui-router-extras'
  gem 'rails-assets-angular-animate'
  gem 'rails-assets-angular-aria'
  gem 'rails-assets-angular-material'
  gem 'rails-assets-angular-material-data-table'
  gem 'rails-assets-angular-uuid4'
  gem 'rails-assets-angular-formly'
  gem 'rails-assets-restangular'
  gem 'rails-assets-api-check'
  gem 'rails-assets-svg-pan-zoom'
end

gem 'webhostinghub-glyphs-rails'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'awesome_print'
  gem "railroady"

  gem 'spring'
end

