source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'rails-api'
gem 'spring', :group => :development
gem "active_model_serializers", github: "rails-api/active_model_serializers"
gem 'docker-api'
gem 'hutch'
gem 'pg'

