# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4650c00ec6f78f4d773ab088b071c78c8955c76d6cffe1e203ceba57a993985d508f9fa0254434a59c0d9d0e98d12c28675e4f662462b60f195acdde65857078

test:
  secret_key_base: 74ad64f7547ac9223567a0e6f2e5dd71ec6b8c577068cc4e96fb0c2f5bf124a78ef3d7161d2a3f899d6ba97a9701943f67562d92a5983328262ec2547395a0d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
