angular.module 'WFMS.Common', []
angular.module 'WFMS.Dashboard', []
angular.module 'WFMS.ProcessDesign', []
angular.module 'WFMS.TabManagement', []
angular.module 'WFMS.User', []
angular.module 'WFMS.Workflow', []
angular.module 'WFMS.WorkflowVersion', []
angular.module 'WFMS.WorkflowBundle', []
