angular.module 'Common', []
angular.module 'Dashboard', []
angular.module 'ProcessDesigner', []
angular.module 'TabManagement', []
angular.module 'User', []
angular.module 'Workflow', []
angular.module 'WorkflowVersion', []
