default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: development_db_1
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: workflow-development-server_development

test:
  <<: *default
  database: workflow-development-server_test

production:
  <<: *default
  database: workflow-development-server_production
  username: workflow-development-server
  password: <%= ENV['WORKFLOW-DEVELOPMENT-SERVER_DATABASE_PASSWORD'] %>
