default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['WORKFLOW-DEVELOPMENT-SERVER_DATABASE'] || 'workflowdevelopmentserver_db_1' %>
  user: workflow_development_server
  password: masterarbeit

development:
  <<: *default
  database: workflow-development-server_development

test:
  <<: *default
  database: workflow-development-server_test

production:
  <<: *default
  database: workflow-development-server_production
  username: workflow-development-server
  password: <%= ENV['WORKFLOW-DEVELOPMENT-SERVER_DATABASE_PASSWORD'] %>
