db:
  image: postgres
  volumes_from:
    - data
  environment:
    POSTGRES_PASSWORD: masterarbeit
    POSTGRES_USER: workflow_development_server
web:
  image: workflow_development_server
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"
  links:
    - db
data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data
